import sys

СЛОВАРЬ_ПЕРЕВОДА = {
    'функция': 'def',
    'класс': 'class',
    'если': 'if',
    'или_если': 'elif',
    'иначе': 'else',
    'пока': 'while',
    'для': 'for',
    ' в ': ' in ',
    'попытка': 'try',
    'ошибка': 'except',
    'наконец': 'finally',
    'вернуть': 'return',
    'прервать': 'break',
    'продолжить': 'continue',
    'пройти': 'pass',
    'импорт': 'import',
    'из': 'from',
    'как': 'as',
    'глобальный': 'global',
    'не_локальный': 'nonlocal',
    'лямбда': 'lambda',
    'выдать': 'raise',
    'утверждать': 'assert',
    'с_': 'with',
    'удалить': 'del',
    'ждать': 'await',
    'асинх': 'async',
    'есть': 'is',
    'не_в': 'not in',
    'есть_не': 'is not',
    'выход': 'yield',
    'выход_из': 'yield from',
    'напечатать': 'print',

    'Истина': 'True',
    'Ложь': 'False',
    'Ничего': 'None',
    'Не_Реализовано': 'NotImplemented',
    'Многоточие': 'Ellipsis',
    'Отладка': '__debug__',

    ' и ': ' and ',
    ' или ': ' or ',
    ' не ': ' not ',

    'печать': 'print',
    'ввод': 'input',
    'целое': 'int',
    'дробное': 'float',
    'текст': 'str',
    'байты': 'bytes',
    'логическое': 'bool',
    'список': 'list',
    'словарь': 'dict',
    'множество': 'set',
    'кортеж': 'tuple',
    'замороженное_множество': 'frozenset',
    'диапазон': 'range',
    'длина': 'len',
    'тип': 'type',
    'объект': 'object',
    'свойство': 'property',
    'статический_метод': 'staticmethod',
    'класс_метод': 'classmethod',
    'супер': 'super',
    'округлить': 'round',
    'минимум': 'min',
    'максимум': 'max',
    'сумма': 'sum',
    'абсолют': 'abs',
    'все_': 'all',
    'любой_': 'any',
    'перечислить': 'enumerate',
    'почтовый': 'zip',
    'фильтр': 'filter',
    'карта': 'map',
    'сортировать': 'sorted',
    'обратить': 'reversed',
    'открыть': 'open',
    'хэш': 'hash',
    'ид': 'id',
    'вызвать': 'callable',
    'экземпляр': 'isinstance',
    'подкласс': 'issubclass',
    'имеет_атрибут': 'hasattr',
    'получить_атрибут': 'getattr',
    'установить_атрибут': 'setattr',
    'удалить_атрибут': 'delattr',
    'представить': 'repr',
    'шестнадцатеричное': 'hex',
    'восьмеричное': 'oct',
    'двоичное': 'bin',
    'символ': 'chr',
    'код_символа': 'ord',
    'формат': 'format',
    'степень': 'pow',
    'частное_и_остаток': 'divmod',
    'помощь': 'help',
    'просмотреть': 'dir',
    'пространство_имён': 'vars',
    'байт_массив': 'bytearray',
    'память': 'memoryview',
    'следующий': 'next',
    'итератор': 'iter',
    'срез': 'slice',
    'комплексное': 'complex',
    'исполняемый': 'exec',
    'вычислить': 'eval',
    'скомпилировать': 'compile',
    'напечатать_ошибку': 'print',
    'выход_из_программы': 'exit',
    'выход_из_системы': 'quit',
    'заморозить': 'frozenset',
    'без_возврата': 'None',
    'бесконечность': 'float("inf")',
    'не_число': 'float("nan")',

    'основание_2': 'base2',
    'основание_8': 'base8',
    'основание_16': 'base16',

    '.верхний_регистр()': '.upper()',
    '.нижний_регистр()': '.lower()',
    '.заменить(': '.replace(',
    '.разбить(': '.split(',
    '.соединить(': '.join(',
    '.начинается_с(': '.startswith(',
    '.заканчивается_на(': '.endswith(',
    '.найти(': '.find(',
    '.убрать_пробелы()': '.strip()',
    '.убрать_слева()': '.lstrip()',
    '.убрать_справа()': '.rstrip()',
    '.посчитать(': '.count(',
    '.заглавная()': '.capitalize()',
    '.заголовок()': '.title()',
    '.поменять_регистр()': '.swapcase()',
    '.это_цифры()': '.isdigit()',
    '.это_буквы()': '.isalpha()',
    '.это_буквы_и_цифры()': '.isalnum()',
    '.это_пробелы()': '.isspace()',
    '.форматировать(': '.format(',
    '.кодировать(': '.encode(',
    '.декодировать(': '.decode(',
    '.разбить_по_строкам()': '.splitlines()',
    '.удалить_префикс(': '.removeprefix(',
    '.удалить_суффикс(': '.removesuffix(',
    '.выровнять_по_центру(': '.center(',
    '.выровнять_влево(': '.ljust(',
    '.выровнять_вправо(': '.rjust(',
    '.заполнить_нулями(': '.zfill(',
    '.табуляция_в_пробелы()': '.expandtabs()',
    '.перевести_таблицу(': '.translate(',
    '.создать_таблицу_перевода(': '.maketrans(',
    '.заканчивается_ли_суффиксом(': '.endswith(',
    '.начинается_ли_префиксом(': '.startswith(',
    '.это_заголовок()': '.istitle()',
    '.это_верхний()': '.isupper()',
    '.это_нижний()': '.islower()',
    '.это_печатные()': '.isprintable()',
    '.это_идентификатор()': '.isidentifier()',
    '.это_числовое()': '.isnumeric()',
    '.это_десятичное()': '.isdecimal()',
    '.разбить_по_максимуму(': '.split(',
    '.найти_справа(': '.rfind(',
    '.индекс_справа(': '.rindex(',
    '.индекс_строки(': '.index(',
    '.партиция(': '.partition(',
    '.партиция_справа(': '.rpartition(',

    '.добавить(': '.append(',
    '.расширить(': '.extend(',
    '.вставить(': '.insert(',
    '.удалить(': '.remove(',
    '.вытащить(': '.pop(',
    '.очистить()': '.clear()',
    '.индекс(': '.index(',
    '.сортировать_на_месте()': '.sort()',
    '.сортировать_на_месте(': '.sort(',
    '.перевернуть()': '.reverse()',
    '.копировать()': '.copy()',

    '.ключи()': '.keys()',
    '.значения()': '.values()',
    '.элементы()': '.items()',
    '.получить(': '.get(',
    '.обновить(': '.update(',
    '.вытащить_ключ(': '.pop(',
    '.удалить_последний()': '.popitem()',
    '.копировать_словарь()': '.copy()',
    '.из_ключей(': '.fromkeys(',
    '.установить_по_умолчанию(': '.setdefault(',

    '.объединить(': '.union(',
    '.пересечение(': '.intersection(',
    '.разность(': '.difference(',
    '.симметричная_разность(': '.symmetric_difference(',
    '.это_подмножество(': '.issubset(',
    '.это_надмножество(': '.issuperset(',
    '.непересекаются(': '.isdisjoint(',
    '.добавить_элемент(': '.add(',
    '.удалить_элемент(': '.discard(',
    '.объединить_на_месте(': '.update(',
    '.пересечение_на_месте(': '.intersection_update(',
    '.разность_на_месте(': '.difference_update(',
    '.симм_разность_на_месте(': '.symmetric_difference_update(',
    '.убрать_элемент(': '.remove(',

    '.читать()': '.read(',
    '.читать_строку()': '.readline()',
    '.читать_строки()': '.readlines()',
    '.записать(': '.write(',
    '.записать_строки(': '.writelines(',
    '.закрыть()': '.close()',
    '.сохранить()': '.flush()',
    '.позиция(': '.seek(',
    '.текущая_позиция()': '.tell()',
    '.обрезать(': '.truncate(',
    '.доступен_для_чтения()': '.readable()',
    '.доступен_для_записи()': '.writable()',
    '.перебрать_строки()': '.readlines()',

    'СОЗДАТЬ_ТАБЛИЦУ': 'CREATE TABLE',
    'ЕСЛИ_НЕ_СУЩЕСТВУЕТ': 'IF NOT EXISTS',
    'ОСНОВНОЙ_КЛЮЧ': 'PRIMARY KEY',
    'АВТО_УВЕЛИЧЕНИЕ': 'AUTOINCREMENT',
    'ЦЕЛОЕ': 'INTEGER',
    'ТЕКСТ': 'TEXT',
    'ДРОБНОЕ': 'REAL',
    'ЛОГИЧЕСКИЙ': 'BOOLEAN',
    'ПО_УМОЛЧАНИЮ': 'DEFAULT',
    'НЕ_ПУСТОЕ': 'NOT NULL',
    'УНИКАЛЬНОЕ': 'UNIQUE',
    'ВНЕШНИЙ_КЛЮЧ': 'FOREIGN KEY',
    'ССЫЛАЕТСЯ_НА': 'REFERENCES',
    'ВСТАВИТЬ_В': 'INSERT INTO',
    'ЗНАЧЕНИЯ': 'VALUES',
    'ОБНОВИТЬ': 'UPDATE',
    'УСТАНОВИТЬ': 'SET',
    'ГДЕ': 'WHERE',
    'УДАЛИТЬ_ИЗ': 'DELETE FROM',
    'ВЫБРАТЬ': 'SELECT',
    'ОТ': 'FROM',
    'ВСЁ': '*',
    'СОЕДИНЕНИЕ': 'JOIN',
    'ЛЕВОЕ_СОЕДИНЕНИЕ': 'LEFT JOIN',
    'ПРАВОЕ_СОЕДИНЕНИЕ': 'RIGHT JOIN',
    'ВНУТРЕННЕЕ_СОЕДИНЕНИЕ': 'INNER JOIN',
    'ВНЕШНЕЕ_СОЕДИНЕНИЕ': 'OUTER JOIN',
    'ГРУППИРОВАТЬ_ПО': 'GROUP BY',
    'СОРТИРОВАТЬ_ПО': 'ORDER BY',
    'ПО_ВОЗРАСТАНИЮ': 'ASC',
    'ПО_УБЫВАНИЮ': 'DESC',
    'ОГРАНИЧИТЬ': 'LIMIT',
    'ПРОПУСТИТЬ': 'OFFSET',
    'МЕЖДУ': 'BETWEEN',
    'КАК_ИМЯ': 'AS',
    'СУЩЕСТВУЕТ': 'EXISTS',
    'ЛЮБОЙ': 'ANY',
    'ВСЕ': 'ALL',
    'ОБЪЕДИНИТЬ': 'UNION',
    'ОБЪЕДИНИТЬ_ВСЕ': 'UNION ALL',
    'ПЕРЕСЕЧЕНИЕ': 'INTERSECT',
    'КРОМЕ': 'EXCEPT',
    'СОЗДАТЬ_ИНДЕКС': 'CREATE INDEX',
    'УДАЛИТЬ_ТАБЛИЦУ': 'DROP TABLE',
    'ИЗМЕНИТЬ_ТАБЛИЦУ': 'ALTER TABLE',
    'ДОБАВИТЬ_СТОЛБЕЦ': 'ADD COLUMN',
    'УДАЛИТЬ_СТОЛБЕЦ': 'DROP COLUMN',
    'ПЕРЕИМЕНОВАТЬ': 'RENAME TO',
    'ТРАНЗАКЦИЯ': 'BEGIN TRANSACTION',
    'ЗАФИКСИРОВАТЬ': 'COMMIT',
    'ОТКАТИТЬ': 'ROLLBACK',
    'ВАКУУМ': 'VACUUM',
    'СЧИТАТЬ': 'COUNT',
    'СРЕДНЕЕ': 'AVG',
    'ИТОГ': 'SUM',
    'МАКСИМАЛЬНОЕ': 'MAX',
    'МИНИМАЛЬНОЕ': 'MIN',
    'ИМЕЯ': 'HAVING',
    'НЕ': 'NOT',
    'И_SQL': 'AND',
    'ИЛИ_SQL': 'OR',
    'В_СПИСКЕ': 'IN',
    'КАК_ШАБЛОН': 'LIKE',
    'НУЛЕВОЕ': 'NULL',
    'НЕ_НУЛЕВОЕ': 'IS NOT NULL',
    'ЯВЛЯЕТСЯ_НУЛЕВЫМ': 'IS NULL',
    'БЛОБ': 'BLOB',
    'ЧИСЛОВОЕ': 'NUMERIC',

    'Исключение': 'Exception',
    'Базовая_Ошибка': 'BaseException',
    'Ошибка_Системы': 'SystemExit',
    'Ошибка_Клавиатуры': 'KeyboardInterrupt',
    'Ошибка_Генератора': 'GeneratorExit',
    'Ошибка_Остановки': 'StopIteration',
    'Ошибка_Арифметики': 'ArithmeticError',
    'Ошибка_Плавающей_Точки': 'FloatingPointError',
    'Ошибка_Переполнения': 'OverflowError',
    'Ошибка_Деления_На_Ноль': 'ZeroDivisionError',
    'Ошибка_Утверждения': 'AssertionError',
    'Ошибка_Атрибута': 'AttributeError',
    'Ошибка_Буфера': 'BufferError',
    'Ошибка_Конца_Файла': 'EOFError',
    'Ошибка_Импорта': 'ImportError',
    'Ошибка_Модуля_Не_Найден': 'ModuleNotFoundError',
    'Ошибка_Поиска': 'LookupError',
    'Ошибка_Индекса': 'IndexError',
    'Ошибка_Ключа': 'KeyError',
    'Ошибка_Памяти': 'MemoryError',
    'Ошибка_Имени': 'NameError',
    'Ошибка_Не_Объявлено': 'UnboundLocalError',
    'Ошибка_Системного_Вызова': 'OSError',
    'Ошибка_Блокировки': 'BlockingIOError',
    'Ошибка_Потомка': 'ChildProcessError',
    'Ошибка_Соединения': 'ConnectionError',
    'Ошибка_Прерванного_Соединения': 'BrokenPipeError',
    'Ошибка_Отклонено': 'ConnectionAbortedError',
    'Ошибка_Отказано': 'ConnectionRefusedError',
    'Ошибка_Сброшено': 'ConnectionResetError',
    'Ошибка_Файл_Существует': 'FileExistsError',
    'Ошибка_Файл_Не_Найден': 'FileNotFoundError',
    'Ошибка_Прерывания': 'InterruptedError',
    'Ошибка_Это_Папка': 'IsADirectoryError',
    'Ошибка_Не_Папка': 'NotADirectoryError',
    'Ошибка_Разрешения': 'PermissionError',
    'Ошибка_Процесса': 'ProcessLookupError',
    'Ошибка_Времени': 'TimeoutError',
    'Ошибка_Ссылки': 'ReferenceError',
    'Ошибка_Исполнения': 'RuntimeError',
    'Ошибка_Не_Реализовано': 'NotImplementedError',
    'Ошибка_Рекурсии': 'RecursionError',
    'Ошибка_Синтаксиса': 'SyntaxError',
    'Ошибка_Отступа': 'IndentationError',
    'Ошибка_Табуляции': 'TabError',
    'Ошибка_Системы_Типов': 'SystemError',
    'Ошибка_Типа': 'TypeError',
    'Ошибка_Значения': 'ValueError',
    'Ошибка_Юникода': 'UnicodeError',
    'Ошибка_Кодирования': 'UnicodeEncodeError',
    'Ошибка_Декодирования': 'UnicodeDecodeError',
    'Ошибка_Перевода_Юникода': 'UnicodeTranslateError',
    'Предупреждение': 'Warning',
    'Предупреждение_Пользователя': 'UserWarning',
    'Предупреждение_Устарело': 'DeprecationWarning',
    'Предупреждение_Синтаксиса': 'SyntaxWarning',
    'Предупреждение_Выполнения': 'RuntimeWarning',
    'Предупреждение_Будущего': 'FutureWarning',
    'Предупреждение_Импорта': 'ImportWarning',
    'Предупреждение_Юникода': 'UnicodeWarning',
    'Предупреждение_Байтов': 'BytesWarning',
    'Предупреждение_Ресурса': 'ResourceWarning',
    'Ошибка_Стоп_Асинхронной_Итерации': 'StopAsyncIteration',
    'Ошибка_Аннотации': 'AnnotationError',
    'Ошибка_Среды': 'EnvironmentError',
    'Ошибка_Ввода_Вывода': 'IOError',
    'Ошибка_Виндовс': 'WindowsError',

    '__имя__': '__name__',
    '__главный__': '__main__',
    '__файл__': '__file__',
    '__документация__': '__doc__',
    '__модуль__': '__module__',
    '__класс__': '__class__',
    '__словарь__': '__dict__',
    '__путь__': '__path__',
    '__пакет__': '__package__',
    '__все__': '__all__',
    '__инициализация__': '__init__',
    '__вызов__': '__call__',
    '__строка__': '__str__',
    '__представление__': '__repr__',
    '__длина__': '__len__',
    '__вход__': '__enter__',
    '__выход__': '__exit__',
    '__сложение__': '__add__',
    '__вычитание__': '__sub__',
    '__умножение__': '__mul__',
    '__деление__': '__truediv__',
    '__равно__': '__eq__',
    '__меньше__': '__lt__',
    '__больше__': '__gt__',
    '__итерация__': '__iter__',
    '__следующий__': '__next__',
    '__содержит__': '__contains__',
    '__получить_элемент__': '__getitem__',
    '__установить_элемент__': '__setitem__',
    '__удалить_элемент__': '__delitem__',
    '__новый__': '__new__',
    '__уничтожить__': '__del__',
    '__хэш__': '__hash__',
    '__логическое__': '__bool__',
    '__не_равно__': '__ne__',
    '__меньше_или_равно__': '__le__',
    '__больше_или_равно__': '__ge__',
    '__сложение_справа__': '__radd__',
    '__вычитание_справа__': '__rsub__',
    '__умножение_справа__': '__rmul__',
    '__деление_справа__': '__rtruediv__',
    '__целочисленное_деление__': '__floordiv__',
    '__остаток__': '__mod__',
    '__степень__': '__pow__',
    '__и_побитовое__': '__and__',
    '__или_побитовое__': '__or__',
    '__исключающее_или__': '__xor__',
    '__инверсия__': '__invert__',
    '__сдвиг_влево__': '__lshift__',
    '__сдвиг_вправо__': '__rshift__',
    '__отрицание__': '__neg__',
    '__положительное__': '__pos__',
    '__абсолют__': '__abs__',
    '__целое__': '__int__',
    '__дробное__': '__float__',
    '__комплексное__': '__complex__',
    '__байты__': '__bytes__',
    '__формат__': '__format__',
    '__атрибут__': '__getattr__',
    '__атрибут_установить__': '__setattr__',
    '__атрибут_удалить__': '__delattr__',
    '__атрибуты__': '__dir__',
    '__аргументы__': '__args__',
    '__аннотации__': '__annotations__',
    '__основания__': '__bases__',
    '__версия__': '__version__',
    '__автор__': '__author__',
    '__спецификация__': '__spec__',
    '__загрузчик__': '__loader__',
    '__кешированный__': '__cached__',
    '__закрытые_ячейки__': '__closure__',
    '__код__': '__code__',
    '__умолчания__': '__defaults__',
    '__глобальные__': '__globals__',
    '__квалификация__': '__qualname__',
    '__обёртка__': '__wrapped__',

    '@статический_метод': '@staticmethod',
    '@класс_метод': '@classmethod',
    '@свойство': '@property',
    '@абстрактный_метод': '@abstractmethod',
    '@переопределить': '@override',
    '@кешировать': '@cache',
    '@кешировать_свойство': '@cached_property',
    '@общий': '@total_ordering',
    '@сингелтон': '@singleton',

    'время': 'time',
    'дата_время': 'datetime',
    'система': 'sys',
    'операционная_система': 'os',
    'потоки': 'threading',
    'случайный': 'random',
    'математика': 'math',
    'статистика': 'statistics',
    'регулярные_выражения': 're',
    'структура_данных': 'collections',
    'итераторы': 'itertools',
    'функциональные_инструменты': 'functools',
    'пути': 'pathlib',
    'сериализация': 'pickle',
    'работа_с_джсон': 'json',
    'работа_с_цсв': 'csv',
    'логирование': 'logging',
    'аргументы': 'argparse',
    'тестирование': 'unittest',
    'копирование': 'copy',
    'перечисления': 'enum',
    'типизация': 'typing',
    'датаклассы': 'dataclasses',
    'десятичные': 'decimal',
    'дроби': 'fractions',
    'хеширование': 'hashlib',
    'работа_с_email': 'email',
    'работа_с_url': 'urllib',
    'работа_с_http': 'http',
    'работа_с_xml': 'xml',
    'работа_с_html': 'html',
    'работа_с_zip': 'zipfile',
    'работа_с_tar': 'tarfile',
    'работа_с_изображениями': 'PIL',
    'сеть': 'socket',
    'асинхронность': 'asyncio',
    'подпроцесс': 'subprocess',
    'шифрование': 'cryptography',
    'база_данных': 'sqlite3',
    'телебот': 'telebot',
    'айограм': 'aiogram',
    'запросы': 'requests',
    'красивый_суп': 'bs4',
    'нампи': 'numpy',
    'пандас': 'pandas',
    'питон_телеграм': 'telegram',
    'очередь': 'queue',
    'многопроцессность': 'multiprocessing',
    'параллелизм': 'concurrent',
    'контекст': 'contextlib',
    'абстракции': 'abc',
    'инспекция': 'inspect',
    'предупреждения': 'warnings',
    'слабые_ссылки': 'weakref',
    'хранилище': 'shelve',
    'база_данных_ключ_значение': 'dbm',
    'сжатие': 'zlib',
    'gzip_файлы': 'gzip',
    'работа_с_конфиг': 'configparser',
    'интерфейс': 'tkinter',
    'рисование': 'turtle',
    'звук': 'wave',
    'шаблоны': 'string',
    'двоичные_данные': 'struct',
    'кодеки': 'codecs',
    'юникод_данные': 'unicodedata',
    'разбор': 'ast',
    'трассировка': 'traceback',
    'стек': 'tracemalloc',
    'профиль': 'cProfile',
    'таймеры': 'timeit',
    'работа_с_датами': 'calendar',
    'зоны_времени': 'zoneinfo',
    'работа_с_числами': 'numbers',
    'шина_данных': 'mmap',
    'сигналы': 'signal',
    'разрешения': 'stat',
    'блокировки': 'fcntl',
    'терминал': 'curses',

    'sqlite3.подключиться(': 'sqlite3.connect(',
    'sqlite3.версия': 'sqlite3.version',
    'sqlite3.версия_sqlite': 'sqlite3.sqlite_version',
    '.курсор()': '.cursor()',
    '.выполнить(': '.execute(',
    '.выполнить_несколько(': '.executemany(',
    '.выполнить_скрипт(': '.executescript(',
    '.получить_одну()': '.fetchone()',
    '.получить_все()': '.fetchall()',
    '.получить_несколько(': '.fetchmany(',
    '.зафиксировать()': '.commit()',
    '.откатить()': '.rollback()',
    '.закрыть_базу()': '.close()',
    '.создать_функцию(': '.create_function(',
    '.создать_агрегат(': '.create_aggregate(',
    '.создать_коллацию(': '.create_collation(',
    '.прервать()': '.interrupt()',
    '.установить_авторизацию(': '.set_authorizer(',
    '.установить_прогресс(': '.set_progress_handler(',
    '.установить_трассировку(': '.set_trace_callback(',
    '.включить_расширение(': '.enable_load_extension(',
    '.загрузить_расширение(': '.load_extension(',
    '.резервная_копия(': '.backup(',
    '.итерировать_дамп()': '.iterdump()',
    'sqlite3.Строка': 'sqlite3.Row',
    'sqlite3.Ошибка_Операции': 'sqlite3.OperationalError',
    'sqlite3.Ошибка_Базы_Данных': 'sqlite3.DatabaseError',
    'sqlite3.Ошибка_Программирования': 'sqlite3.ProgrammingError',
    'sqlite3.Ошибка_Интерфейса': 'sqlite3.InterfaceError',
    'sqlite3.Ошибка_Целостности': 'sqlite3.IntegrityError',
    'sqlite3.Ошибка_Данных': 'sqlite3.DataError',
    'sqlite3.Ошибка_Предупреждение': 'sqlite3.Warning',
    'sqlite3.Ошибка_Не_Поддерживается': 'sqlite3.NotSupportedError',
    'sqlite3.РАЗБОР_ИМЁН_СТОЛБЦОВ': 'sqlite3.PARSE_COLNAMES',
    'sqlite3.РАЗБОР_ДЕКЛАРАЦИЙ': 'sqlite3.PARSE_DECLTYPES',
    'sqlite3.адаптировать(': 'sqlite3.adapt(',
    'sqlite3.зарегистрировать_адаптер(': 'sqlite3.register_adapter(',
    'sqlite3.зарегистрировать_конвертер(': 'sqlite3.register_converter(',
    'sqlite3.полное_имя_модуля': 'sqlite3.apilevel',
    'sqlite3.безопасность_потоков': 'sqlite3.threadsafety',
    'sqlite3.формат_параметров': 'sqlite3.paramstyle',

    'telebot.ТелеБот(': 'telebot.TeleBot(',
    'telebot.типы': 'telebot.types',
    'telebot.форматирование': 'telebot.formatting',
    'telebot.утилиты': 'telebot.util',
    'telebot.Фильтры': 'telebot.custom_filters',
    'telebot.исключения': 'telebot.apihelper',
    '.отправить_сообщение(': '.send_message(',
    '.отправить_фото(': '.send_photo(',
    '.отправить_документ(': '.send_document(',
    '.отправить_видео(': '.send_video(',
    '.отправить_аудио(': '.send_audio(',
    '.отправить_голос(': '.send_voice(',
    '.отправить_видео_заметку(': '.send_video_note(',
    '.отправить_стикер(': '.send_sticker(',
    '.отправить_местоположение(': '.send_location(',
    '.отправить_место(': '.send_venue(',
    '.отправить_контакт(': '.send_contact(',
    '.отправить_опрос(': '.send_poll(',
    '.отправить_кубик(': '.send_dice(',
    '.отправить_группу_медиа(': '.send_media_group(',
    '.отправить_действие(': '.send_chat_action(',
    '.переслать_сообщение(': '.forward_message(',
    '.скопировать_сообщение(': '.copy_message(',
    '.изменить_сообщение(': '.edit_message_text(',
    '.изменить_подпись(': '.edit_message_caption(',
    '.изменить_медиа(': '.edit_message_media(',
    '.изменить_кнопки(': '.edit_message_reply_markup(',
    '.удалить_сообщение(': '.delete_message(',
    '.закрепить_сообщение(': '.pin_chat_message(',
    '.открепить_сообщение(': '.unpin_chat_message(',
    '.открепить_все_сообщения(': '.unpin_all_chat_messages(',
    '.ответить(': '.reply_to(',
    '.получить_обновления(': '.get_updates(',
    '.получить_информацию(': '.get_me()',
    '.получить_фото_профиля(': '.get_user_profile_photos(',
    '.получить_файл(': '.get_file(',
    '.скачать_файл(': '.download_file(',
    '.получить_чат(': '.get_chat(',
    '.получить_участников_чата(': '.get_chat_members_count(',
    '.получить_участника_чата(': '.get_chat_member(',
    '.исключить_участника(': '.ban_chat_member(',
    '.разбанить_участника(': '.unban_chat_member(',
    '.ограничить_участника(': '.restrict_chat_member(',
    '.продвинуть_участника(': '.promote_chat_member(',
    '.установить_заголовок_чата(': '.set_chat_title(',
    '.установить_описание_чата(': '.set_chat_description(',
    '.установить_фото_чата(': '.set_chat_photo(',
    '.удалить_фото_чата()': '.delete_chat_photo()',
    '.создать_ссылку_чата(': '.create_chat_invite_link(',
    '.экспортировать_ссылку_чата()': '.export_chat_invite_link()',
    '.ответить_на_запрос(': '.answer_callback_query(',
    '.ответить_на_инлайн(': '.answer_inline_query(',
    '.запустить_опрос(': '.poll()',
    '.запустить_опрос_webhook(': '.webhook()',
    '.обработчик_сообщений(': '.message_handler(',
    '.обработчик_кнопок(': '.callback_query_handler(',
    '.обработчик_инлайн(': '.inline_handler(',
    '.обработчик_канала(': '.channel_post_handler(',
    '.обработчик_редактирования(': '.edited_message_handler(',
    '.зарегистрировать_фильтр(': '.add_custom_filter(',
    '.бесконечный_опрос(': '.infinity_polling(',
    '.остановить_опрос()': '.stop_polling()',
    '.удалить_webhook()': '.delete_webhook()',
    '.установить_webhook(': '.set_webhook(',
    '.получить_webhook()': '.get_webhook_info()',
    'telebot.типы.Сообщение': 'telebot.types.Message',
    'telebot.типы.КнопкаОтвета': 'telebot.types.ReplyKeyboardMarkup',
    'telebot.типы.КнопкаУдаления': 'telebot.types.ReplyKeyboardRemove',
    'telebot.типы.ВстроеннаяКнопка': 'telebot.types.InlineKeyboardMarkup',
    'telebot.типы.ВстроеннаяКнопкаРяд': 'telebot.types.InlineKeyboardButton',
    'telebot.типы.КнопкаРяд': 'telebot.types.KeyboardButton',
    'telebot.типы.ЗапросКнопки': 'telebot.types.CallbackQuery',
    'telebot.типы.ВстроенныйЗапрос': 'telebot.types.InlineQuery',
    'telebot.типы.ВстроенныйРезультатСтатья': 'telebot.types.InlineQueryResultArticle',
    'telebot.типы.ВстроенныйРезультатФото': 'telebot.types.InlineQueryResultPhoto',
    'telebot.типы.ВстроенныйРезультатВидео': 'telebot.types.InlineQueryResultVideo',
    'telebot.типы.ВстроенныйРезультатАудио': 'telebot.types.InlineQueryResultAudio',
    'telebot.типы.ВстроенныйРезультатДокумент': 'telebot.types.InlineQueryResultDocument',
    'telebot.типы.ВстроенныйРезультатГиф': 'telebot.types.InlineQueryResultGif',
    'telebot.типы.ВстроенныйКонтентСообщения': 'telebot.types.InputTextMessageContent',
    'telebot.типы.Пользователь': 'telebot.types.User',
    'telebot.типы.Чат': 'telebot.types.Chat',
    'telebot.типы.Фото': 'telebot.types.PhotoSize',
    'telebot.типы.Документ': 'telebot.types.Document',
    'telebot.типы.Аудио': 'telebot.types.Audio',
    'telebot.типы.Видео': 'telebot.types.Video',
    'telebot.типы.Голос': 'telebot.types.Voice',
    'telebot.типы.Стикер': 'telebot.types.Sticker',
    'telebot.типы.МестоположениеТип': 'telebot.types.Location',
    'telebot.типы.Контакт': 'telebot.types.Contact',
    'telebot.типы.Файл': 'telebot.types.File',
    'telebot.типы.Форсировать_Ответ': 'telebot.types.ForceReply',
    'telebot.типы.Права_Участника': 'telebot.types.ChatPermissions',
    'telebot.типы.Команда_Бота': 'telebot.types.BotCommand',
    'telebot.типы.Меню_Команд': 'telebot.types.BotCommandScope',
    'telebot.типы.Опрос': 'telebot.types.Poll',
    'telebot.типы.ВариантОпроса': 'telebot.types.PollOption',
    'telebot.типы.Кубик': 'telebot.types.Dice',
    'telebot.типы.ИнпутМедиаФото': 'telebot.types.InputMediaPhoto',
    'telebot.типы.ИнпутМедиаВидео': 'telebot.types.InputMediaVideo',
    'telebot.типы.ИнпутМедиаДокумент': 'telebot.types.InputMediaDocument',
    'telebot.типы.ИнпутМедиаАудио': 'telebot.types.InputMediaAudio',
    'telebot.форматирование.жирный(': 'telebot.formatting.mbold(',
    'telebot.форматирование.курсив(': 'telebot.formatting.mitalic(',
    'telebot.форматирование.код(': 'telebot.formatting.mcode(',
    'telebot.форматирование.ссылка(': 'telebot.formatting.mlink(',
    'telebot.форматирование.подчёркнутый(': 'telebot.formatting.munderline(',
    'telebot.форматирование.зачёркнутый(': 'telebot.formatting.mstrikethrough(',
    'telebot.форматирование.спойлер(': 'telebot.formatting.mspoiler(',
    'РАЗМЕТКА_HTML': 'parse_mode="HTML"',
    'РАЗМЕТКА_MARKDOWN': 'parse_mode="Markdown"',
    'РАЗМЕТКА_MARKDOWN_V2': 'parse_mode="MarkdownV2"',

    'aiogram.Бот(': 'aiogram.Bot(',
    'aiogram.Диспетчер(': 'aiogram.Dispatcher(',
    'aiogram.Роутер(': 'aiogram.Router(',
    'aiogram.Фильтр': 'aiogram.F',
    'aiogram.типы': 'aiogram.types',
    'aiogram.фильтры': 'aiogram.filters',
    'aiogram.исключения': 'aiogram.exceptions',
    'aiogram.утилиты': 'aiogram.utils',
    'aiogram.машина_состояний': 'aiogram.fsm',
    'aiogram.промежуточный': 'aiogram.middleware',
    'aiogram.вебхук': 'aiogram.webhook',
    'aiogram.типы.Сообщение': 'aiogram.types.Message',
    'aiogram.типы.КнопкаОтвета': 'aiogram.types.ReplyKeyboardMarkup',
    'aiogram.типы.КнопкаУдаления': 'aiogram.types.ReplyKeyboardRemove',
    'aiogram.типы.ВстроеннаяКнопка': 'aiogram.types.InlineKeyboardMarkup',
    'aiogram.типы.ВстроеннаяКнопкаКнопка': 'aiogram.types.InlineKeyboardButton',
    'aiogram.типы.КнопкаРяд': 'aiogram.types.KeyboardButton',
    'aiogram.типы.КнопкаБилдер': 'aiogram.utils.keyboard.ReplyKeyboardBuilder',
    'aiogram.типы.ВстроенныйБилдер': 'aiogram.utils.keyboard.InlineKeyboardBuilder',
    'aiogram.типы.ЗапросКнопки': 'aiogram.types.CallbackQuery',
    'aiogram.типы.ВстроенныйЗапрос': 'aiogram.types.InlineQuery',
    'aiogram.типы.Пользователь': 'aiogram.types.User',
    'aiogram.типы.Чат': 'aiogram.types.Chat',
    'aiogram.типы.Фото': 'aiogram.types.PhotoSize',
    'aiogram.типы.Документ': 'aiogram.types.Document',
    'aiogram.типы.Аудио': 'aiogram.types.Audio',
    'aiogram.типы.Видео': 'aiogram.types.Video',
    'aiogram.типы.Голос': 'aiogram.types.Voice',
    'aiogram.типы.Стикер': 'aiogram.types.Sticker',
    'aiogram.типы.МестоположениеТип': 'aiogram.types.Location',
    'aiogram.типы.Контакт': 'aiogram.types.Contact',
    'aiogram.типы.Файл': 'aiogram.types.File',
    'aiogram.типы.Опрос': 'aiogram.types.Poll',
    'aiogram.типы.ВариантОпроса': 'aiogram.types.PollOption',
    'aiogram.типы.Кубик': 'aiogram.types.Dice',
    'aiogram.типы.ИнпутМедиаФото': 'aiogram.types.InputMediaPhoto',
    'aiogram.типы.ИнпутМедиаВидео': 'aiogram.types.InputMediaVideo',
    'aiogram.типы.ИнпутМедиаДокумент': 'aiogram.types.InputMediaDocument',
    'aiogram.типы.ИнпутМедиаАудио': 'aiogram.types.InputMediaAudio',
    'aiogram.типы.БизнесСоединение': 'aiogram.types.BusinessConnection',
    'aiogram.типы.Права_Участника': 'aiogram.types.ChatPermissions',
    'aiogram.типы.Права_Администратора': 'aiogram.types.ChatAdministratorRights',
    'aiogram.типы.Команда_Бота': 'aiogram.types.BotCommand',
    'aiogram.типы.Область_Команд': 'aiogram.types.BotCommandScope',
    'aiogram.типы.ОтветВебАпп': 'aiogram.types.WebAppInfo',
    'aiogram.типы.Данные_ВебАпп': 'aiogram.types.WebAppData',
    'aiogram.типы.Параметры_Меню': 'aiogram.types.MenuButton',
    'aiogram.типы.Ответ_Форсировать': 'aiogram.types.ForceReply',
    'aiogram.типы.ВстроенныйРезультатСтатья': 'aiogram.types.InlineQueryResultArticle',
    'aiogram.типы.ВстроенныйРезультатФото': 'aiogram.types.InlineQueryResultPhoto',
    'aiogram.типы.ВстроенныйРезультатВидео': 'aiogram.types.InlineQueryResultVideo',
    'aiogram.типы.ВстроенныйРезультатАудио': 'aiogram.types.InlineQueryResultAudio',
    'aiogram.типы.ВстроенныйКонтентСообщения': 'aiogram.types.InputTextMessageContent',
    'aiogram.типы.Обновление': 'aiogram.types.Update',
    'aiogram.типы.ОтветЗапросПред_Оплаты': 'aiogram.types.PreCheckoutQuery',
    'aiogram.типы.ОтветЗапросОплаты': 'aiogram.types.ShippingQuery',
    'aiogram.типы.Успешный_Платёж': 'aiogram.types.SuccessfulPayment',
    'aiogram.типы.Счёт': 'aiogram.types.Invoice',
    'aiogram.типы.Участник_Чата': 'aiogram.types.ChatMember',
    'aiogram.типы.Участник_Владелец': 'aiogram.types.ChatMemberOwner',
    'aiogram.типы.Участник_Администратор': 'aiogram.types.ChatMemberAdministrator',
    'aiogram.типы.Участник_Обычный': 'aiogram.types.ChatMemberMember',
    'aiogram.типы.Участник_Ограничен': 'aiogram.types.ChatMemberRestricted',
    'aiogram.типы.Участник_Вышел': 'aiogram.types.ChatMemberLeft',
    'aiogram.типы.Участник_Забанен': 'aiogram.types.ChatMemberBanned',
    'aiogram.типы.Обновление_Участника': 'aiogram.types.ChatMemberUpdated',
    'aiogram.типы.Анимация': 'aiogram.types.Animation',
    'aiogram.типы.Видео_Заметка': 'aiogram.types.VideoNote',
    'aiogram.фильтры.Команда(': 'aiogram.filters.Command(',
    'aiogram.фильтры.НачалоКоманды(': 'aiogram.filters.CommandStart(',
    'aiogram.фильтры.ПомощьКоманды(': 'aiogram.filters.CommandHelp(',
    'aiogram.фильтры.МагическийФильтр(': 'aiogram.filters.MagicData(',
    'aiogram.фильтры.СостояниеФильтр(': 'aiogram.filters.StateFilter(',
    'aiogram.фильтры.ТекстФильтр(': 'aiogram.filters.Text(',
    'aiogram.фильтры.Регулярка(': 'aiogram.filters.Regexp(',
    'aiogram.машина_состояний.Состояние': 'aiogram.fsm.state.State',
    'aiogram.машина_состояний.ГруппаСостояний': 'aiogram.fsm.state.StatesGroup',
    'aiogram.машина_состояний.Контекст': 'aiogram.fsm.context.FSMContext',
    'aiogram.машина_состояний.ПамятьХранилище': 'aiogram.fsm.storage.memory.MemoryStorage',
    'aiogram.машина_состояний.РедисХранилище': 'aiogram.fsm.storage.redis.RedisStorage',
    'aiogram.исключения.ТелеграмОшибка': 'aiogram.exceptions.TelegramAPIError',
    'aiogram.исключения.ЗапрещёноОшибка': 'aiogram.exceptions.TelegramForbiddenError',
    'aiogram.исключения.НеНайденоОшибка': 'aiogram.exceptions.TelegramNotFound',
    'aiogram.исключения.КонфликтОшибка': 'aiogram.exceptions.TelegramConflictError',
    'aiogram.исключения.СлишкомМногоЗапросов': 'aiogram.exceptions.TelegramRetryAfter',
    'aiogram.утилиты.форматирование.жирный(': 'aiogram.utils.formatting.Bold(',
    'aiogram.утилиты.форматирование.курсив(': 'aiogram.utils.formatting.Italic(',
    'aiogram.утилиты.форматирование.код(': 'aiogram.utils.formatting.Code(',
    'aiogram.утилиты.форматирование.ссылка(': 'aiogram.utils.formatting.TextLink(',
    'aiogram.утилиты.форматирование.подчёркнутый(': 'aiogram.utils.formatting.Underline(',
    'aiogram.утилиты.форматирование.зачёркнутый(': 'aiogram.utils.formatting.Strikethrough(',
    'aiogram.утилиты.форматирование.спойлер(': 'aiogram.utils.formatting.Spoiler(',
    'aiogram.утилиты.форматирование.предварительный(': 'aiogram.utils.formatting.Pre(',
    'aiogram.утилиты.форматирование.текст(': 'aiogram.utils.formatting.Text(',
    'aiogram.утилиты.форматирование.отформатировать(': 'aiogram.utils.formatting.as_marked_section(',
    'aiogram.утилиты.ссылка_пользователя(': 'aiogram.utils.link.create_tg_link(',
    'aiogram.утилиты.запуск(': 'aiogram.utils.executor.start_polling(',
    'asyncio.запустить(': 'asyncio.run(',
    'asyncio.получить_цикл()': 'asyncio.get_event_loop()',
    'asyncio.создать_задачу(': 'asyncio.create_task(',
    'asyncio.собрать(': 'asyncio.gather(',
    'asyncio.ждать(': 'asyncio.sleep(',
    'asyncio.Очередь(': 'asyncio.Queue(',
    'asyncio.Событие(': 'asyncio.Event(',
    'asyncio.Семафор(': 'asyncio.Semaphore(',
    'asyncio.Блокировка(': 'asyncio.Lock(',
    '.запустить(': '.start(',
    '.остановить()': '.stop()',
    '.включить(': '.start_polling(',
    '.диспетчер': '.dp',
    '.маршрутизатор': '.router',
    '.включить_маршрутизатор(': '.include_router(',
    '.обработчик_сообщений': '.message',
    '.обработчик_кнопок_встроенных': '.callback_query',
    '.обработчик_инлайна': '.inline_query',
    '.обработчик_канала': '.channel_post',
    '.обработчик_редактирования_сообщения': '.edited_message',
    '.промежуточный_слой': '.middleware',
    '.зарегистрировать_промежуточный(': '.middleware.register(',
    '.ответить(': '.answer(',
    '.ответить_фото(': '.answer_photo(',
    '.ответить_документ(': '.answer_document(',
    '.ответить_видео(': '.answer_video(',
    '.ответить_аудио(': '.answer_audio(',
    '.ответить_голос(': '.answer_voice(',
    '.ответить_стикер(': '.answer_sticker(',
    '.ответить_местоположение(': '.answer_location(',
    '.ответить_место(': '.answer_venue(',
    '.ответить_контакт(': '.answer_contact(',
    '.ответить_опрос(': '.answer_poll(',
    '.ответить_кубик(': '.answer_dice(',
    '.ответить_группу_медиа(': '.answer_media_group(',
    '.ответить_действие(': '.answer_chat_action(',
    '.изменить_текст(': '.edit_text(',
    '.изменить_подпись(': '.edit_caption(',
    '.изменить_медиа(': '.edit_media(',
    '.изменить_кнопки(': '.edit_reply_markup(',
    '.удалить()': '.delete()',
    '.переслать(': '.forward(',
    '.скопировать(': '.copy_to(',
    '.закрепить()': '.pin(',
    '.открепить()': '.unpin()',
    '.получить_состояние()': '.get_state()',
    '.установить_состояние(': '.set_state(',
    '.очистить_состояние()': '.clear()',
    '.обновить_данные(': '.update_data(',
    '.получить_данные()': '.get_data()',
    '.установить_данные(': '.set_data(',
    '.текст': '.text',
    '.данные': '.data',
    '.от': '.from_user',
    '.идентификатор': '.id',
    '.имя': '.first_name',
    '.фамилия': '.last_name',
    '.псевдоним': '.username',
    '.чат': '.chat',
    '.идентификатор_чата': '.chat.id',
    '.тип_чата': '.chat.type',
    '.заголовок_чата': '.chat.title',
    '.сообщение_ид': '.message_id',
    '.дата': '.date',
    '.фото': '.photo',
    '.документ': '.document',
    '.аудио': '.audio',
    '.видео': '.video',
    '.голос': '.voice',
    '.стикер': '.sticker',
    '.местоположение': '.location',
    '.контакт': '.contact',
    '.анимация': '.animation',
    '.опрос': '.poll',
    '.кубик': '.dice',
    '.ответ_на': '.reply_to_message',
    '.подпись': '.caption',
    '.сущности': '.entities',
    '.файл_ид': '.file_id',
    '.уникальный_файл_ид': '.file_unique_id',
    '.размер_файла': '.file_size',
    '.имя_файла': '.file_name',
    '.тип_файла': '.mime_type',
    '.ширина': '.width',
    '.высота': '.height',
    '.длительность': '.duration',
    '.эскиз': '.thumbnail',
    '.язык': '.language_code',
    '.бот': '.is_bot',
    '.премиум': '.is_premium',
    '.биография': '.bio',
    '.количество_участников': '.member_count',
    '.описание': '.description',
    '.ссылка_приглашения': '.invite_link',
    '.фото_чата': '.photo',
    '.закреплённое_сообщение': '.pinned_message',
    '.права': '.permissions',
    '.замедление': '.slow_mode_delay',
    '.токен': '.token',
}


def перевести_код(русский_код):
    результат = русский_код
    for рус, англ in СЛОВАРЬ_ПЕРЕВОДА.items():
        результат = результат.replace(рус, англ)
    return результат


def перевести_файл(путь_вход, путь_выход=None):
    with open(путь_вход, 'r', encoding='utf-8') as ф:
        русский_код = ф.read()

    переведенный = перевести_код(русский_код)

    if путь_выход is None:
        путь_выход = путь_вход.replace('.rpy', '.py')
        if путь_выход == путь_вход:
            путь_выход = путь_вход + '.py'

    with open(путь_выход, 'w', encoding='utf-8') as ф:
        ф.write(переведенный)

    return путь_выход


def показать_все_переводы():
    печать = print
    печать("Все доступные переводы:")
    печать("-" * 50)
    for рус, англ in СЛОВАРЬ_ПЕРЕВОДА.items():
        print(f"  {рус!r:45} -> {англ!r}")


def найти_перевод(запрос):
    результаты = {}
    запрос_нижний = запрос.lower()
    for рус, англ in СЛОВАРЬ_ПЕРЕВОДА.items():
        if запрос_нижний in рус.lower() or запрос_нижний in англ.lower():
            результаты[рус] = англ
    return результаты


def main():
    if len(sys.argv) < 2:
        print("RPython — Русский Python")
        print("Использование:")
        print("  rpython файл.rpy [выход.py]    — перевести файл")
        print("  rpython --список               — показать все переводы")
        print("  rpython --найти <запрос>       — найти перевод")
        sys.exit(1)

    if sys.argv[1] == '--список':
        показать_все_переводы()
        return

    if sys.argv[1] == '--найти' and len(sys.argv) > 2:
        запрос = sys.argv[2]
        найденные = найти_перевод(запрос)
        if найденные:
            print(f"Найдено {len(найденные)} совпадений для '{запрос}':")
            for рус, англ in найденные.items():
                print(f"  {рус!r:45} -> {англ!r}")
        else:
            print(f"Ничего не найдено для '{запрос}'")
        return

    путь_вход = sys.argv[1]
    путь_выход = sys.argv[2] if len(sys.argv) > 2 else None

    результат = перевести_файл(путь_вход, путь_выход)
    print(f"✅ {путь_вход} → {результат}")


if __name__ == '__main__':
    main()
